name: Build Tweak

on:
  push:
    branches:
      - master
  

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Install Dependencies
      run: brew install ldid fakeroot wget

    - name: install build sdk
      run: |
        wget https://crafterpika.ml/downloads/build_sdk.zip
        unzip build_sdk.zip
        ls
        rm -rf /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk/
        mv iPhoneOS13.1.sdk /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk/

    - name: Setup Theos
      uses: actions/checkout@master
      with:
        repository: theos/theos
        ref: 8771215f765e774bfefdacc6ddf0e151c2973d49
        path: theos
        submodules: recursive

    - name: Build Package
      env:
        THEOS: theos
      run: make package

    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: build-${{ steps.vars.outputs.sha_short }}
        path: packages
      
