name: Build Tweak

on:
  push:
    branches:
      - master
  

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Install Dependencies
      run: brew install ldid fakeroot

    - name: Setup Theos
      uses: actions/checkout@master
      with:
        repository: theos/theos
        ref: 8771215f765e774bfefdacc6ddf0e151c2973d49
        path: theos
        submodules: recursive

    - name: Build Package
      env:
        THEOS: theos
      run: make package
